apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-service
  name: frontend-service
spec:
  ports:
  - name: "8180"
    port: 8180
    protocol: TCP
    targetPort: 8180
  selector:
    app: frontend-deployment
  type: ClusterIP
